/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qiyi_tp_cinema_MainActivity */

#ifndef _Included_com_qiyi_tp_cinema_MainActivity
#define _Included_com_qiyi_tp_cinema_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qiyi_tp_cinema_MainActivity
 * Method:    hellofantasy
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qiyi_tp_cinema_MainActivity_hellofantasy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
